# Generated by Django 4.2.1 on 2024-01-16 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("paypal_authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="paypaltoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
