# Generated by Django 4.2.1 on 2023-05-15 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpay", "0002_paypalinfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Scopes",
            new_name="Scope",
        ),
    ]
