# Generated by Django 4.2.1 on 2023-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("access_type", models.CharField(max_length=255)),
                ("app_id", models.CharField(max_length=255)),
                ("expires_in", models.CharField(max_length=255)),
                ("nonce", models.CharField(max_length=255)),
                ("scopes", models.ManyToManyField(to="djpay.scopes")),
            ],
        ),
    ]
