# Generated by Django 4.2.1 on 2023-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djpay", "0003_rename_scopes_scope"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paypaltoken",
            old_name="cliend_id",
            new_name="client_id",
        ),
    ]
