# Generated by Django 4.2.1 on 2023-05-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djpay", "0004_rename_cliend_id_paypaltoken_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalinfo",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
