# Generated by Django 4.2.1 on 2023-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djpay", "0006_paypalinfo_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalinfo",
            name="base_url",
            field=models.URLField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
