# Generated by Django 4.2.1 on 2023-06-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("djpay", "0007_paypalinfo_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalinfo",
            name="tokens",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djpay.paypaltoken",
            ),
        ),
    ]
