# Generated by Django 4.2.1 on 2023-06-02 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djpay", "0010_rename_access_type_paypalinfo_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paypalinfo",
            name="tokens",
        ),
        migrations.AddField(
            model_name="paypaltoken",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
