# Generated by Django 4.2.1 on 2023-07-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djpay", "0011_remove_paypalinfo_tokens_paypaltoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypaltoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
