name: Flake8 Lint

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  lint:
    name: Run Flake8 Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  # Set the Python version you want to use

      - name: Install Flake8
        run: python -m pip install flake8

      - name: Run Flake8
        run: flake8
