name: Run Tests

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  # Set the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file path

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: core.settings
        run: python -B -m pytest
